# Generated by Django 4.2.7 on 2024-03-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_managers_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default='static/posts/post.jpg', upload_to='media/posts/'),
        ),
    ]
