# Generated by Django 4.2.7 on 2024-03-18 18:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_posts_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
