# Generated by Django 4.2.7 on 2024-03-18 19:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
