# Generated by Django 4.2.7 on 2024-03-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_comments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
